Repository Team-UMC/UMC-Server, pull requests merged in 2024-01, with the labels that each got.

#2 [CI] ci/cd setting
  .github/workflows/umc-service-dev.yml
  .github/workflows/umc-service-prod.yml
  .gitignore
  Dockerfile
  docker-compose.dev.yml
  docker-compose.prod.yml
  src/main/java/com/umc/networkingService/domain/test/controller/TestController.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.properties
Labels: 👷ci, ✨ feature

#4 Ci/#1/ci cd setting
  .github/workflows/umc-service-dev.yml
  .github/workflows/umc-service-prod.yml
  docker-compose.dev.yml
  docker-compose.prod.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: 👷ci, 🚨 hotfix

#6 [FEAT] Swagger setting
  .github/workflows/umc-service-dev.yml
  .github/workflows/umc-service-prod.yml
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/com/umc/networkingService/config/SwaggerConfig.java
  src/main/java/com/umc/networkingService/domain/test/controller/TestController.java
Labels: ✨ feature, 📝 docs

#8 [FEAT] Entity mapping
  .gitignore
  src/main/java/com/umc/networkingService/NetworkingServiceApplication.java
  src/main/java/com/umc/networkingService/domain/album/entity/Album.java
  src/main/java/com/umc/networkingService/domain/album/entity/AlbumComment.java
  src/main/java/com/umc/networkingService/domain/album/entity/AlbumHeart.java
  src/main/java/com/umc/networkingService/domain/album/entity/AlbumImage.java
  src/main/java/com/umc/networkingService/domain/board/entity/Board.java
  src/main/java/com/umc/networkingService/domain/board/entity/BoardCheck.java
  src/main/java/com/umc/networkingService/domain/board/entity/BoardComment.java
  src/main/java/com/umc/networkingService/domain/board/entity/BoardHeart.java
  src/main/java/com/umc/networkingService/domain/board/entity/BoardImage.java
  src/main/java/com/umc/networkingService/domain/board/entity/BoardType.java
  src/main/java/com/umc/networkingService/domain/board/entity/HostType.java
  src/main/java/com/umc/networkingService/domain/branch/entity/Branch.java
  src/main/java/com/umc/networkingService/domain/branch/entity/BranchUniversity.java
  src/main/java/com/umc/networkingService/domain/friend/entity/Friend.java
  src/main/java/com/umc/networkingService/domain/inviteCode/entity/InviteCode.java
  src/main/java/com/umc/networkingService/domain/mascot/entity/Mascot.java
  src/main/java/com/umc/networkingService/domain/member/entity/Member.java
  src/main/java/com/umc/networkingService/domain/member/entity/MemberPoint.java
  src/main/java/com/umc/networkingService/domain/member/entity/PointType.java
  src/main/java/com/umc/networkingService/domain/member/entity/Position.java
  src/main/java/com/umc/networkingService/domain/member/entity/SocialType.java
  src/main/java/com/umc/networkingService/domain/message/entity/Message.java
  src/main/java/com/umc/networkingService/domain/message/entity/MessageRoom.java
  src/main/java/com/umc/networkingService/domain/project/entity/Project.java
  src/main/java/com/umc/networkingService/domain/project/entity/ProjectHeart.java
  src/main/java/com/umc/networkingService/domain/project/entity/ProjectMember.java
  src/main/java/com/umc/networkingService/domain/project/entity/Type.java
  src/main/java/com/umc/networkingService/domain/proposal/entity/Proposal.java
  src/main/java/com/umc/networkingService/domain/proposal/entity/proposalImage.java
  src/main/java/com/umc/networkingService/domain/schedule/entity/Schedule.java
  src/main/java/com/umc/networkingService/domain/session/entity/Session.java
  src/main/java/com/umc/networkingService/domain/todayILearned/entity/TodayILearned.java
  src/main/java/com/umc/networkingService/domain/todayILearned/entity/TodayILearnedFile.java
  src/main/java/com/umc/networkingService/domain/todoList/entity/ToDoList.java
  src/main/java/com/umc/networkingService/domain/university/entity/University.java
  src/main/java/com/umc/networkingService/global/common/BaseEntity.java
  src/main/java/com/umc/networkingService/global/common/BaseResponse.java
  src/main/java/com/umc/networkingService/global/common/Part.java
  src/main/java/com/umc/networkingService/global/common/Role.java
  src/main/java/com/umc/networkingService/global/common/Semester.java
  src/main/resources/application-dev.yml
Labels: ✨ feature

#12 [FEAT] S3 관련 초기 설정 및 함수 구현
  build.gradle
  src/main/java/com/umc/networkingService/config/S3Config.java
  src/main/java/com/umc/networkingService/domain/album/entity/AlbumHeart.java
  src/main/java/com/umc/networkingService/domain/board/entity/Board.java
  src/main/java/com/umc/networkingService/domain/branch/entity/BranchUniversity.java
  src/main/java/com/umc/networkingService/domain/file/controller/FileController.java
  src/main/java/com/umc/networkingService/domain/file/dto/response/FileCreateResponse.java
  src/main/java/com/umc/networkingService/domain/file/service/FileService.java
  src/main/java/com/umc/networkingService/domain/file/service/FileServiceImpl.java
  src/main/java/com/umc/networkingService/domain/friend/entity/Friend.java
  src/main/java/com/umc/networkingService/domain/mascot/entity/Mascot.java
  src/main/java/com/umc/networkingService/domain/member/entity/MemberPoint.java
  src/main/java/com/umc/networkingService/domain/message/entity/Message.java
  src/main/java/com/umc/networkingService/domain/message/entity/MessageRoom.java
  src/main/java/com/umc/networkingService/domain/project/entity/Project.java
  src/main/java/com/umc/networkingService/domain/project/entity/ProjectHeart.java
  src/main/java/com/umc/networkingService/domain/project/entity/ProjectMember.java
  src/main/java/com/umc/networkingService/domain/proposal/entity/Proposal.java
  src/main/java/com/umc/networkingService/domain/schedule/entity/Schedule.java
  src/main/java/com/umc/networkingService/domain/todayILearned/entity/TodayILearned.java
  src/main/java/com/umc/networkingService/domain/todayILearned/entity/TodayILearnedFile.java
  src/main/java/com/umc/networkingService/domain/todoList/entity/ToDoList.java
  src/main/java/com/umc/networkingService/domain/university/entity/University.java
  src/main/java/com/umc/networkingService/global/common/BaseEntity.java
  src/main/java/com/umc/networkingService/global/utils/S3FileComponent.java
Labels: ✨ feature, ♻️ refactor

#13 [FEAT] API 응답 통일 & 에러 핸들러 설정
  build.gradle
  src/main/java/com/umc/networkingService/domain/album/entity/Album.java
  src/main/java/com/umc/networkingService/domain/album/entity/AlbumComment.java
  src/main/java/com/umc/networkingService/domain/album/entity/AlbumHeart.java
  src/main/java/com/umc/networkingService/domain/album/entity/AlbumImage.java
  src/main/java/com/umc/networkingService/domain/board/entity/Board.java
  src/main/java/com/umc/networkingService/domain/board/entity/BoardCheck.java
  src/main/java/com/umc/networkingService/domain/board/entity/BoardComment.java
  src/main/java/com/umc/networkingService/domain/board/entity/BoardHeart.java
  src/main/java/com/umc/networkingService/domain/board/entity/BoardImage.java
  src/main/java/com/umc/networkingService/domain/branch/entity/Branch.java
  src/main/java/com/umc/networkingService/domain/branch/entity/BranchUniversity.java
  src/main/java/com/umc/networkingService/domain/friend/entity/Friend.java
  src/main/java/com/umc/networkingService/domain/inviteCode/entity/InviteCode.java
  src/main/java/com/umc/networkingService/domain/mascot/entity/Mascot.java
  src/main/java/com/umc/networkingService/domain/member/entity/Member.java
  src/main/java/com/umc/networkingService/domain/member/entity/MemberPoint.java
  src/main/java/com/umc/networkingService/domain/message/entity/Message.java
  src/main/java/com/umc/networkingService/domain/message/entity/MessageRoom.java
  src/main/java/com/umc/networkingService/domain/project/entity/Project.java
  src/main/java/com/umc/networkingService/domain/project/entity/ProjectHeart.java
  src/main/java/com/umc/networkingService/domain/project/entity/ProjectMember.java
  src/main/java/com/umc/networkingService/domain/proposal/entity/Proposal.java
  src/main/java/com/umc/networkingService/domain/proposal/entity/proposalImage.java
  src/main/java/com/umc/networkingService/domain/schedule/entity/Schedule.java
  src/main/java/com/umc/networkingService/domain/session/entity/Session.java
  src/main/java/com/umc/networkingService/domain/test/controller/TestController.java
  src/main/java/com/umc/networkingService/domain/test/dto/TestRequest.java
  src/main/java/com/umc/networkingService/domain/test/dto/TestResponse.java
  src/main/java/com/umc/networkingService/domain/test/service/TestService.java
  src/main/java/com/umc/networkingService/domain/todayILearned/entity/TodayILearned.java
  src/main/java/com/umc/networkingService/domain/todayILearned/entity/TodayILearnedFile.java
  src/main/java/com/umc/networkingService/domain/todoList/entity/ToDoList.java
  src/main/java/com/umc/networkingService/domain/university/entity/University.java
  src/main/java/com/umc/networkingService/global/common/BaseResponse.java
  src/main/java/com/umc/networkingService/global/common/base/BaseEntity.java
  src/main/java/com/umc/networkingService/global/common/base/BaseResponse.java
  src/main/java/com/umc/networkingService/global/common/exception/ErrorCode.java
  src/main/java/com/umc/networkingService/global/common/exception/ExceptionAdvice.java
  src/main/java/com/umc/networkingService/global/common/exception/RestApiException.java
Labels: ✨ feature

#14 [FEAT] : redis를 이용한 refreshToken 저장
  build.gradle
  docker-compose.dev.yml
  src/main/java/com/umc/networkingService/config/RedisConfig.java
  src/main/java/com/umc/networkingService/domain/member/entity/RefreshToken.java
  src/main/java/com/umc/networkingService/domain/member/repository/RefreshTokenRepository.java
  src/main/java/com/umc/networkingService/domain/member/service/RefreshTokenService.java
  src/test/java/com/umc/networkingService/RefreshTokenServiceIntegrationTest.java
Labels: ✨ feature

#31 [FEAT] 소셜 로그인 기능 구현
  build.gradle
  src/main/java/com/umc/networkingService/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/umc/networkingService/config/security/jwt/TokenInfo.java
  src/main/java/com/umc/networkingService/domain/member/client/AppleMemberClient.java
  src/main/java/com/umc/networkingService/domain/member/client/GoogleMemberClient.java
  src/main/java/com/umc/networkingService/domain/member/client/KakaoMemberClient.java
  src/main/java/com/umc/networkingService/domain/member/client/NaverMemberClient.java
  src/main/java/com/umc/networkingService/domain/member/controller/MemberController.java
  src/main/java/com/umc/networkingService/domain/member/dto/MemberResponseDto.java
  src/main/java/com/umc/networkingService/domain/member/dto/client/AppleResponse.java
  src/main/java/com/umc/networkingService/domain/member/dto/client/GoogleResponse.java
  src/main/java/com/umc/networkingService/domain/member/dto/client/KakaoResponse.java
  src/main/java/com/umc/networkingService/domain/member/dto/client/NaverResponse.java
  src/main/java/com/umc/networkingService/domain/member/dto/response/MemberLoginResponse.java
  src/main/java/com/umc/networkingService/domain/member/entity/Member.java
  src/main/java/com/umc/networkingService/domain/member/entity/RefreshToken.java
  src/main/java/com/umc/networkingService/domain/member/entity/SocialType.java
  src/main/java/com/umc/networkingService/domain/member/mapper/MemberMapper.java
  src/main/java/com/umc/networkingService/domain/member/repository/MemberRepository.java
  src/main/java/com/umc/networkingService/domain/member/service/MemberService.java
  src/main/java/com/umc/networkingService/domain/member/service/MemberServiceImpl.java
  src/test/java/com/umc/networkingService/domain/member/controller/MemberControllerTest.java
  src/test/java/com/umc/networkingService/domain/member/service/MemberServiceIntegrationTest.java
Labels: ✨ feature, 📝 docs

#33 [FEAT] 초대 코드 관련 API 구현
  src/main/java/com/umc/networkingService/config/security/auth/PrincipalDetails.java
  src/main/java/com/umc/networkingService/domain/invite/controller/InviteController.java
  src/main/java/com/umc/networkingService/domain/invite/dto/response/InviteAuthenticateResponse.java
  src/main/java/com/umc/networkingService/domain/invite/dto/response/InviteCreateResponse.java
  src/main/java/com/umc/networkingService/domain/invite/dto/response/InviteInquiryMineResponse.java
  src/main/java/com/umc/networkingService/domain/invite/entity/Invite.java
  src/main/java/com/umc/networkingService/domain/invite/mapper/InviteMapper.java
  src/main/java/com/umc/networkingService/domain/invite/repository/InviteRepository.java
  src/main/java/com/umc/networkingService/domain/invite/service/InviteService.java
  src/main/java/com/umc/networkingService/domain/invite/service/InviteServiceImpl.java
  src/main/java/com/umc/networkingService/domain/member/controller/MemberController.java
  src/main/java/com/umc/networkingService/domain/member/dto/response/MemberAuthenticateGithubResponse.java
  src/main/java/com/umc/networkingService/domain/member/entity/Member.java
  src/main/java/com/umc/networkingService/domain/member/service/AuthService.java
  src/main/java/com/umc/networkingService/domain/member/service/AuthServiceImpl.java
  src/main/java/com/umc/networkingService/domain/member/service/MemberPositionServiceImpl.java
  src/main/java/com/umc/networkingService/domain/member/service/MemberService.java
  src/main/java/com/umc/networkingService/domain/member/service/MemberServiceImpl.java
  src/main/java/com/umc/networkingService/global/common/exception/ErrorCode.java
  src/test/java/com/umc/networkingService/domain/invite/controller/InviteControllerTest.java
  src/test/java/com/umc/networkingService/domain/invite/service/InviteServiceIntegrationTest.java
  src/test/java/com/umc/networkingService/domain/member/controller/AuthControllerTest.java
  src/test/java/com/umc/networkingService/domain/member/controller/MemberControllerTest.java
  src/test/java/com/umc/networkingService/domain/member/service/AuthServiceIntegrationTest.java
  src/test/java/com/umc/networkingService/domain/member/service/MemberServiceIntegrationTest.java
  src/test/java/com/umc/networkingService/support/ControllerTestConfig.java
  src/test/java/com/umc/networkingService/support/ServiceIntegrationTestConfig.java
Labels: ✨ feature, 📝 docs, 🐛 bug

#38 [Feat] 투두리스트 API 구현
  src/main/java/com/umc/networkingService/domain/todoList/controller/TodoListController.java
  src/main/java/com/umc/networkingService/domain/todoList/dto/request/TodoListCreateRequest.java
  src/main/java/com/umc/networkingService/domain/todoList/dto/request/TodoListUpdateRequest.java
  src/main/java/com/umc/networkingService/domain/todoList/dto/response/TodoListGetResponse.java
  src/main/java/com/umc/networkingService/domain/todoList/dto/response/TodoListGetResponses.java
  src/main/java/com/umc/networkingService/domain/todoList/dto/response/TodoListIdResponse.java
  src/main/java/com/umc/networkingService/domain/todoList/entity/ToDoList.java
  src/main/java/com/umc/networkingService/domain/todoList/mapper/TodoListMapper.java
  src/main/java/com/umc/networkingService/domain/todoList/repository/TodoListRepository.java
  src/main/java/com/umc/networkingService/domain/todoList/service/TodoListService.java
  src/main/java/com/umc/networkingService/domain/todoList/service/TodoListServiceImpl.java
  src/main/java/com/umc/networkingService/global/common/exception/ErrorCode.java
  src/main/resources/application-local.yml
Labels: ✨ feature

#40 [FEAT] 스케줄 API 구현
  src/main/java/com/umc/networkingService/domain/schedule/controller/ScheduleController.java
  src/main/java/com/umc/networkingService/domain/schedule/controller/StaffScheduleController.java
  src/main/java/com/umc/networkingService/domain/schedule/dto/request/ScheduleRequest.java
  src/main/java/com/umc/networkingService/domain/schedule/dto/response/ScheduleResponse.java
  src/main/java/com/umc/networkingService/domain/schedule/entity/Schedule.java
  src/main/java/com/umc/networkingService/domain/schedule/mapper/ScheduleMapper.java
  src/main/java/com/umc/networkingService/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/umc/networkingService/domain/schedule/service/ScheduleService.java
  src/main/java/com/umc/networkingService/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/com/umc/networkingService/global/common/exception/ErrorCode.java
Labels: ✨ feature

#43 [FEAT] 유저의 마지막 활동 시간 기록 기능 및 온라인 상태 확인 기능 구현
  src/main/java/com/umc/networkingService/config/WebMvcConfig.java
  src/main/java/com/umc/networkingService/domain/invite/controller/InviteController.java
  src/main/java/com/umc/networkingService/domain/invite/dto/response/InviteInquiryMineResponse.java
  src/main/java/com/umc/networkingService/domain/invite/mapper/InviteMapper.java
  src/main/java/com/umc/networkingService/domain/invite/service/InviteService.java
  src/main/java/com/umc/networkingService/domain/invite/service/InviteServiceImpl.java
  src/main/java/com/umc/networkingService/domain/member/controller/AuthController.java
  src/main/java/com/umc/networkingService/domain/member/controller/StaffMemberController.java
  src/main/java/com/umc/networkingService/domain/member/dto/response/MemberSearchInfoResponse.java
  src/main/java/com/umc/networkingService/domain/member/dto/response/MemberSearchInfosResponse.java
  src/main/java/com/umc/networkingService/domain/member/entity/Member.java
  src/main/java/com/umc/networkingService/domain/member/interceptor/LastActiveInterceptor.java
  src/main/java/com/umc/networkingService/domain/member/mapper/MemberMapper.java
  src/main/java/com/umc/networkingService/domain/member/service/AuthServiceImpl.java
  src/main/java/com/umc/networkingService/domain/member/service/MemberService.java
  src/main/java/com/umc/networkingService/domain/member/service/MemberServiceImpl.java
  src/main/java/com/umc/networkingService/domain/schedule/controller/ScheduleController.java
  src/main/java/com/umc/networkingService/domain/schedule/controller/StaffScheduleController.java
  src/main/java/com/umc/networkingService/domain/schedule/dto/request/ScheduleRequest.java
  src/main/java/com/umc/networkingService/domain/schedule/dto/response/ScheduleResponse.java
  src/main/java/com/umc/networkingService/domain/schedule/entity/Schedule.java
  src/main/java/com/umc/networkingService/domain/schedule/mapper/ScheduleMapper.java
  src/main/java/com/umc/networkingService/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/umc/networkingService/domain/schedule/service/ScheduleService.java
  src/main/java/com/umc/networkingService/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/com/umc/networkingService/domain/session/entity/Session.java
  src/main/java/com/umc/networkingService/domain/todoList/controller/TodoListController.java
  src/main/java/com/umc/networkingService/domain/todoList/dto/response/TodoListIdResponse.java
  src/main/java/com/umc/networkingService/domain/todoList/service/TodoListService.java
  src/main/java/com/umc/networkingService/domain/todoList/service/TodoListServiceImpl.java
  src/test/java/com/umc/networkingService/domain/invite/controller/InviteControllerTest.java
  src/test/java/com/umc/networkingService/domain/invite/service/InviteServiceIntegrationTest.java
  src/test/java/com/umc/networkingService/domain/member/controller/StaffMemberControllerTest.java
  src/test/java/com/umc/networkingService/domain/member/service/MemberServiceIntegrationTest.java
Labels: ✨ feature
