Repository Team-UMC/UMC-Server, pull requests merged in 2024-02, with the labels that each got.

#44 [FEAT] 친구 관련 API 구현
  src/main/java/com/umc/networkingService/domain/friend/controller/FriendController.java
  src/main/java/com/umc/networkingService/domain/friend/dto/response/FriendIdResponse.java
  src/main/java/com/umc/networkingService/domain/friend/dto/response/FriendInquiryByStatusResponse.java
  src/main/java/com/umc/networkingService/domain/friend/mapper/FriendMapper.java
  src/main/java/com/umc/networkingService/domain/friend/repository/FriendRepository.java
  src/main/java/com/umc/networkingService/domain/friend/service/FriendService.java
  src/main/java/com/umc/networkingService/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/umc/networkingService/domain/friend/service/FriendShipService.java
  src/main/java/com/umc/networkingService/domain/friend/service/FriendShipServiceImpl.java
  src/main/java/com/umc/networkingService/domain/member/controller/AuthController.java
  src/main/java/com/umc/networkingService/domain/member/controller/MemberController.java
  src/main/java/com/umc/networkingService/domain/member/entity/Member.java
  src/main/java/com/umc/networkingService/domain/member/repository/MemberRepository.java
  src/main/java/com/umc/networkingService/domain/member/service/AuthServiceImpl.java
  src/main/java/com/umc/networkingService/domain/member/service/MemberService.java
  src/main/java/com/umc/networkingService/domain/member/service/MemberServiceImpl.java
  src/main/java/com/umc/networkingService/global/common/base/swagger/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/umc/networkingService/global/common/exception/ErrorCode.java
  src/test/java/com/umc/networkingService/domain/friend/controller/FriendControllerTest.java
  src/test/java/com/umc/networkingService/domain/friend/service/FriendServiceIntegrationTest.java
  src/test/java/com/umc/networkingService/domain/friend/service/FriendShipServiceImplIntegrationTest.java
  src/test/java/com/umc/networkingService/domain/invite/controller/InviteControllerTest.java
  src/test/java/com/umc/networkingService/domain/member/controller/MemberControllerTest.java
  src/test/java/com/umc/networkingService/domain/member/service/AuthServiceIntegrationTest.java
  src/test/java/com/umc/networkingService/domain/member/service/MemberServiceIntegrationTest.java
  src/test/java/com/umc/networkingService/support/ControllerTestConfig.java
  src/test/java/com/umc/networkingService/support/ServiceIntegrationTestConfig.java
Labels: ✨ feature, 📝 docs

#55 [FEAT] 초기 데이터 설정
  src/main/java/com/umc/networkingService/config/initial/BranchInfo.java
  src/main/java/com/umc/networkingService/config/initial/DataLoader.java
  src/main/java/com/umc/networkingService/config/initial/ProjectInfo.java
  src/main/java/com/umc/networkingService/config/initial/UniversityInfo.java
  src/main/java/com/umc/networkingService/domain/branch/entity/BranchUniversity.java
  src/main/java/com/umc/networkingService/domain/branch/repository/BranchRepository.java
  src/main/java/com/umc/networkingService/domain/branch/repository/BranchUniversityRepository.java
  src/main/java/com/umc/networkingService/domain/branch/service/BranchUniversityService.java
  src/main/java/com/umc/networkingService/domain/branch/service/BranchUniversityServiceImpl.java
  src/main/java/com/umc/networkingService/domain/member/entity/Member.java
  src/main/java/com/umc/networkingService/domain/member/service/AuthServiceImpl.java
  src/main/java/com/umc/networkingService/domain/member/service/MemberServiceImpl.java
  src/main/java/com/umc/networkingService/domain/project/entity/Project.java
  src/main/java/com/umc/networkingService/domain/project/repository/ProjectRepository.java
  src/main/java/com/umc/networkingService/domain/university/repository/UniversityRepository.java
  src/main/java/com/umc/networkingService/global/common/enums/Semester.java
  src/main/java/com/umc/networkingService/global/common/exception/ErrorCode.java
Labels: ✨ feature

#54 [FIX] 스케줄 레포지토리 findScheduleByYearAndMonth 인자 수정
  src/main/java/com/umc/networkingService/domain/schedule/repository/ScheduleRepository.java
Labels: 🚨 hotfix

#58 [FIX] 깃허브 연동하기 임시 수정 및 테스트 코드 에러 해결
  src/main/java/com/umc/networkingService/domain/board/dto/response/BoardDetailResponse.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/BoardSearchPageResponse.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/notice/BoardNoticePageResponse.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/notice/BoardNoticePagingResponse.java
  src/main/java/com/umc/networkingService/domain/branch/repository/BranchRepository.java
  src/main/java/com/umc/networkingService/domain/friend/controller/FriendController.java
  src/main/java/com/umc/networkingService/domain/friend/service/FriendShipServiceImpl.java
  src/main/java/com/umc/networkingService/domain/member/controller/MemberController.java
  src/main/java/com/umc/networkingService/domain/member/entity/Member.java
  src/main/java/com/umc/networkingService/domain/member/repository/MemberRepository.java
  src/main/java/com/umc/networkingService/domain/member/service/AuthServiceImpl.java
  src/main/java/com/umc/networkingService/domain/member/service/MemberService.java
  src/main/java/com/umc/networkingService/domain/member/service/MemberServiceImpl.java
  src/main/java/com/umc/networkingService/domain/project/entity/Project.java
  src/main/java/com/umc/networkingService/domain/todayILearned/controller/TodayILearnedController.java
  src/main/java/com/umc/networkingService/domain/todayILearned/dto/requeest/TodayILearnedRequest.java
  src/main/java/com/umc/networkingService/domain/todayILearned/dto/response/TodayILearnedResponse.java
  src/main/java/com/umc/networkingService/domain/todayILearned/entity/TodayILearned.java
  src/main/java/com/umc/networkingService/domain/todayILearned/mapper/TodayILearnedMapper.java
  src/main/java/com/umc/networkingService/domain/todayILearned/repository/TodayILearnedFileRepository.java
  src/main/java/com/umc/networkingService/domain/todayILearned/repository/TodayILearnedRepository.java
  src/main/java/com/umc/networkingService/domain/todayILearned/service/TodayILearnedFileService.java
  src/main/java/com/umc/networkingService/domain/todayILearned/service/TodayILearnedFileServiceImpl.java
  src/main/java/com/umc/networkingService/domain/todayILearned/service/TodayILearnedService.java
  src/main/java/com/umc/networkingService/domain/todayILearned/service/TodayILearnedServiceImpl.java
  src/main/java/com/umc/networkingService/global/common/enums/Role.java
  src/main/java/com/umc/networkingService/global/common/exception/ErrorCode.java
  src/main/java/com/umc/networkingService/global/common/exception/ExceptionAdvice.java
  src/test/java/com/umc/networkingService/domain/board/controller/BoardControllerTest.java
  src/test/java/com/umc/networkingService/domain/board/controller/BoardControllerTestConfig.java
  src/test/java/com/umc/networkingService/domain/board/service/BoardServiceIntegrationTest.java
  src/test/java/com/umc/networkingService/domain/board/service/BoardServiceTestConfig.java
  src/test/java/com/umc/networkingService/domain/friend/controller/FriendControllerTest.java
  src/test/java/com/umc/networkingService/domain/friend/service/FriendServiceIntegrationTest.java
  src/test/java/com/umc/networkingService/domain/invite/controller/InviteControllerTest.java
  src/test/java/com/umc/networkingService/domain/invite/service/InviteServiceIntegrationTest.java
  src/test/java/com/umc/networkingService/domain/member/controller/MemberControllerTest.java
  src/test/java/com/umc/networkingService/domain/member/service/AuthServiceIntegrationTest.java
  src/test/java/com/umc/networkingService/domain/member/service/MemberServiceIntegrationTest.java
  src/test/java/com/umc/networkingService/support/ServiceIntegrationTestConfig.java
Labels: ♻️ refactor, 🐛 bug

#49 [FEAT] 지부 api 구현
  src/main/java/com/umc/networkingService/config/initial/BranchInfo.java
  src/main/java/com/umc/networkingService/config/security/auth/PrincipalDetails.java
  src/main/java/com/umc/networkingService/domain/branch/controller/BranchController.java
  src/main/java/com/umc/networkingService/domain/branch/controller/StaffBranchController.java
  src/main/java/com/umc/networkingService/domain/branch/dto/request/BranchRequest.java
  src/main/java/com/umc/networkingService/domain/branch/dto/response/BranchResponse.java
  src/main/java/com/umc/networkingService/domain/branch/entity/Branch.java
  src/main/java/com/umc/networkingService/domain/branch/mapper/BranchMapper.java
  src/main/java/com/umc/networkingService/domain/branch/repository/BranchRepository.java
  src/main/java/com/umc/networkingService/domain/branch/repository/BranchUniversityRepository.java
  src/main/java/com/umc/networkingService/domain/branch/service/BranchServiceImpl.java
  src/main/java/com/umc/networkingService/domain/branch/service/BranchUniversityServiceImpl.java
  src/main/java/com/umc/networkingService/domain/branch/validation/annotation/ExistBranch.java
  src/main/java/com/umc/networkingService/domain/branch/validation/validater/ExistBranchValidator.java
  src/main/java/com/umc/networkingService/domain/mascot/entity/Mascot.java
  src/main/java/com/umc/networkingService/domain/university/service/UniversityService.java
  src/main/java/com/umc/networkingService/domain/university/service/UniversityServiceImpl.java
  src/main/java/com/umc/networkingService/global/common/exception/code/BranchErrorCode.java
  src/main/resources/application-local.yml
  src/test/java/com/umc/networkingService/domain/branch/service/BranchServiceTest.java
  src/test/java/com/umc/networkingService/domain/branch/service/BranchUniversityServiceTest.java
  src/test/java/com/umc/networkingService/support/ServiceIntegrationTestConfig.java
Labels: ✨ feature

#65 Feature/#62/login apple
  src/main/java/com/umc/networkingService/domain/member/client/AppleMemberClient.java
  src/main/java/com/umc/networkingService/domain/member/dto/client/ApplePublicKeyResponse.java
  src/main/java/com/umc/networkingService/domain/member/service/AuthServiceImpl.java
  src/main/java/com/umc/networkingService/global/common/exception/code/AuthErrorCode.java
Labels: ✨ feature

#66 [REFACTOR,FIX] BOARD API 리팩토링, 수정
  src/main/java/com/umc/networkingService/domain/board/controller/BoardCommentController.java
  src/main/java/com/umc/networkingService/domain/board/controller/BoardController.java
  src/main/java/com/umc/networkingService/domain/board/controller/StaffBoardController.java
  src/main/java/com/umc/networkingService/domain/board/dto/request/BoardCommentRequest.java
  src/main/java/com/umc/networkingService/domain/board/dto/request/BoardCreateRequest.java
  src/main/java/com/umc/networkingService/domain/board/dto/request/BoardRequest.java
  src/main/java/com/umc/networkingService/domain/board/dto/request/BoardUpdateRequest.java
  src/main/java/com/umc/networkingService/domain/board/dto/request/comment/BoardCommentAddRequest.java
  src/main/java/com/umc/networkingService/domain/board/dto/request/comment/BoardCommentUpdateRequest.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/BoardCommentResponse.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/BoardDetailResponse.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/BoardIdResponse.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/BoardPageResponse.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/BoardPagingResponse.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/BoardResponse.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/BoardSearchPageResponse.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/BoardSearchPagingResponse.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/MyBoardResponse.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/comment/BoardCommentIdResponse.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/comment/BoardCommentPageResponse.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/comment/BoardCommentPagingResponse.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/member/MyBoardCommentPageWebResponse.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/member/MyBoardCommentPagingWebResponse.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/member/MyBoardPageResponse.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/member/MyBoardPagingResponse.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/notice/BoardNoticePageResponse.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/notice/BoardNoticePagingResponse.java
  src/main/java/com/umc/networkingService/domain/board/entity/Board.java
  src/main/java/com/umc/networkingService/domain/board/entity/BoardComment.java
  src/main/java/com/umc/networkingService/domain/board/mapper/BoardCommentMapper.java
  src/main/java/com/umc/networkingService/domain/board/mapper/BoardMapper.java
  src/main/java/com/umc/networkingService/domain/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/umc/networkingService/domain/board/service/BoardCommentService.java
  src/main/java/com/umc/networkingService/domain/board/service/BoardCommentServiceImpl.java
  src/main/java/com/umc/networkingService/domain/board/service/BoardService.java
  src/main/java/com/umc/networkingService/domain/board/service/BoardServiceImpl.java
  src/main/java/com/umc/networkingService/domain/board/service/StaffBoardService.java
  src/main/java/com/umc/networkingService/domain/board/service/StaffBoardServiceImpl.java
  src/test/java/com/umc/networkingService/domain/board/controller/BoardControllerTest.java
  src/test/java/com/umc/networkingService/domain/board/controller/BoardControllerTestConfig.java
  src/test/java/com/umc/networkingService/domain/board/service/BoardServiceIntegrationTest.java
Labels: ♻️ refactor, 🐛 bug

#64 [FEAT] 포인트 획득 기능 구현
  src/main/java/com/umc/networkingService/config/initial/BranchInfo.java
  src/main/java/com/umc/networkingService/config/initial/DataLoader.java
  src/main/java/com/umc/networkingService/config/security/auth/PrincipalDetailsService.java
  src/main/java/com/umc/networkingService/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/umc/networkingService/domain/friend/controller/FriendController.java
  src/main/java/com/umc/networkingService/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/umc/networkingService/domain/invite/service/InviteServiceImpl.java
  src/main/java/com/umc/networkingService/domain/member/client/GithubMemberClient.java
  src/main/java/com/umc/networkingService/domain/member/client/GoogleMemberClient.java
  src/main/java/com/umc/networkingService/domain/member/client/KakaoMemberClient.java
  src/main/java/com/umc/networkingService/domain/member/client/NaverMemberClient.java
  src/main/java/com/umc/networkingService/domain/member/controller/MemberController.java
  src/main/java/com/umc/networkingService/domain/member/dto/response/MemberAttendResponse.java
  src/main/java/com/umc/networkingService/domain/member/entity/Member.java
  src/main/java/com/umc/networkingService/domain/member/mapper/MemberMapper.java
  src/main/java/com/umc/networkingService/domain/member/service/AuthServiceImpl.java
  src/main/java/com/umc/networkingService/domain/member/service/MemberPositionServiceImpl.java
  src/main/java/com/umc/networkingService/domain/member/service/MemberService.java
  src/main/java/com/umc/networkingService/domain/member/service/MemberServiceImpl.java
  src/main/java/com/umc/networkingService/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/com/umc/networkingService/domain/test/service/TestService.java
  src/main/java/com/umc/networkingService/domain/todayILearned/controller/TodayILearnedController.java
  src/main/java/com/umc/networkingService/domain/todayILearned/dto/response/TodayILearnedResponse.java
  src/main/java/com/umc/networkingService/domain/todayILearned/repository/TodayILearnedRepository.java
  src/main/java/com/umc/networkingService/domain/todayILearned/service/TodayILearnedService.java
  src/main/java/com/umc/networkingService/domain/todayILearned/service/TodayILearnedServiceImpl.java
  src/main/java/com/umc/networkingService/domain/todoList/controller/TodoListController.java
  src/main/java/com/umc/networkingService/domain/todoList/dto/response/TodoListCompleteResponse.java
  src/main/java/com/umc/networkingService/domain/todoList/repository/TodoListRepository.java
  src/main/java/com/umc/networkingService/domain/todoList/service/TodoListService.java
  src/main/java/com/umc/networkingService/domain/todoList/service/TodoListServiceImpl.java
  src/main/java/com/umc/networkingService/global/common/exception/code/ToDoListErrorCode.java
  src/main/java/com/umc/networkingService/global/utils/S3FileComponent.java
  src/main/resources/application-local.yml
Labels: ✨ feature, ♻️ refactor, 🐛 bug

#69 [FIX] TIL 수정
  src/main/java/com/umc/networkingService/domain/board/service/BoardFileServiceImpl.java
  src/main/java/com/umc/networkingService/domain/todayILearned/controller/TodayILearnedController.java
  src/main/java/com/umc/networkingService/domain/todayILearned/dto/requeest/TodayILearnedRequest.java
  src/main/java/com/umc/networkingService/domain/todayILearned/repository/TodayILearnedFileRepository.java
  src/main/java/com/umc/networkingService/domain/todayILearned/service/TodayILearnedFileService.java
  src/main/java/com/umc/networkingService/domain/todayILearned/service/TodayILearnedFileServiceImpl.java
  src/main/java/com/umc/networkingService/domain/todayILearned/service/TodayILearnedService.java
  src/main/java/com/umc/networkingService/domain/todayILearned/service/TodayILearnedServiceImpl.java
Labels: 🐛 bug

#71 [FEAT] 마스코트 데이터 설정 및 서버 시간 수정
  src/main/java/com/umc/networkingService/NetworkingServiceApplication.java
  src/main/java/com/umc/networkingService/config/initial/DataLoader.java
  src/main/java/com/umc/networkingService/config/initial/MascotInfo.java
  src/main/java/com/umc/networkingService/config/initial/UniversityInfo.java
  src/main/java/com/umc/networkingService/domain/mascot/entity/Mascot.java
  src/main/java/com/umc/networkingService/domain/mascot/repository/MascotRepository.java
  src/main/java/com/umc/networkingService/domain/university/dto/response/UniversityResponse.java
  src/main/java/com/umc/networkingService/domain/university/mapper/UniversityMapper.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/test/java/com/umc/networkingService/domain/university/service/UniversityServiceIntegrationTest.java
Labels: ✨ feature, 🐛 bug

#76 [S3] 대용량 파일 처리 설정
  src/main/java/com/umc/networkingService/global/common/exception/code/S3ErrorCode.java
  src/main/java/com/umc/networkingService/global/utils/S3FileComponent.java
Labels: ✨ feature, 🚨 hotfix

#79 [FEAT] 프로젝트 API 및 프로젝트 멤버 데이터 세팅
  src/main/java/com/umc/networkingService/config/initial/DataLoader.java
  src/main/java/com/umc/networkingService/config/initial/ProjectInfo.java
  src/main/java/com/umc/networkingService/config/initial/ProjectMemberInfo.java
  src/main/java/com/umc/networkingService/domain/branch/controller/BranchController.java
  src/main/java/com/umc/networkingService/domain/branch/controller/StaffBranchController.java
  src/main/java/com/umc/networkingService/domain/branch/dto/request/BranchRequest.java
  src/main/java/com/umc/networkingService/domain/branch/dto/response/BranchResponse.java
  src/main/java/com/umc/networkingService/domain/branch/service/BranchServiceImpl.java
  src/main/java/com/umc/networkingService/domain/branch/validation/validater/ExistBranchValidator.java
  src/main/java/com/umc/networkingService/domain/mascot/entity/Mascot.java
  src/main/java/com/umc/networkingService/domain/mascot/service/MascotServiceImpl.java
  src/main/java/com/umc/networkingService/domain/member/service/MemberService.java
  src/main/java/com/umc/networkingService/domain/project/controller/ProjectController.java
  src/main/java/com/umc/networkingService/domain/project/controller/StaffProjectController.java
  src/main/java/com/umc/networkingService/domain/project/dto/request/ProjectCreateRequest.java
  src/main/java/com/umc/networkingService/domain/project/dto/request/ProjectUpdateRequest.java
  src/main/java/com/umc/networkingService/domain/project/dto/response/ProjectAllResponse.java
  src/main/java/com/umc/networkingService/domain/project/dto/response/ProjectDetailResponse.java
  src/main/java/com/umc/networkingService/domain/project/dto/response/ProjectIdResponse.java
  src/main/java/com/umc/networkingService/domain/project/entity/Project.java
  src/main/java/com/umc/networkingService/domain/project/entity/ProjectHeart.java
  src/main/java/com/umc/networkingService/domain/project/entity/ProjectMember.java
  src/main/java/com/umc/networkingService/domain/project/entity/ProjectType.java
  src/main/java/com/umc/networkingService/domain/project/mapper/ProjectMapper.java
  src/main/java/com/umc/networkingService/domain/project/repository/ProjectMemberRepository.java
  src/main/java/com/umc/networkingService/domain/project/repository/ProjectRepository.java
  src/main/java/com/umc/networkingService/domain/project/service/ProjectService.java
  src/main/java/com/umc/networkingService/domain/project/service/ProjectServiceImpl.java
  src/main/java/com/umc/networkingService/domain/schedule/controller/ScheduleController.java
  src/main/java/com/umc/networkingService/domain/schedule/dto/request/ScheduleRequest.java
  src/main/java/com/umc/networkingService/domain/schedule/dto/response/ScheduleResponse.java
  src/main/java/com/umc/networkingService/domain/schedule/entity/Schedule.java
  src/main/java/com/umc/networkingService/domain/schedule/mapper/ScheduleMapper.java
  src/main/java/com/umc/networkingService/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/umc/networkingService/domain/schedule/service/ScheduleService.java
  src/main/java/com/umc/networkingService/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/com/umc/networkingService/domain/university/controller/StaffUniversityController.java
  src/main/java/com/umc/networkingService/domain/university/controller/UniversityController.java
  src/main/java/com/umc/networkingService/domain/university/dto/request/UniversityRequest.java
  src/main/java/com/umc/networkingService/domain/university/dto/response/UniversityResponse.java
  src/main/java/com/umc/networkingService/domain/university/service/UniversityServiceImpl.java
  src/main/java/com/umc/networkingService/global/common/exception/ErrorCode.java
  src/main/java/com/umc/networkingService/global/common/exception/code/ProjectErrorCode.java
  src/main/java/com/umc/networkingService/global/common/validation/annotation/ExistProjectName.java
  src/main/java/com/umc/networkingService/global/common/validation/validator/ProjectNameValidator.java
Labels: ✨ feature

#60 [FEAT] 사진첩 API 구현
  src/main/java/com/umc/networkingService/domain/album/controller/AlbumCommentController.java
  src/main/java/com/umc/networkingService/domain/album/controller/AlbumController.java
  src/main/java/com/umc/networkingService/domain/album/dto/request/AlbumCommentCreateRequest.java
  src/main/java/com/umc/networkingService/domain/album/dto/request/AlbumCommentUpdateRequest.java
  src/main/java/com/umc/networkingService/domain/album/dto/request/AlbumCreateRequest.java
  src/main/java/com/umc/networkingService/domain/album/dto/request/AlbumUpdateRequest.java
  src/main/java/com/umc/networkingService/domain/album/dto/response/AlbumCommentIdResponse.java
  src/main/java/com/umc/networkingService/domain/album/dto/response/AlbumDetailResponse.java
  src/main/java/com/umc/networkingService/domain/album/dto/response/AlbumIdResponse.java
  src/main/java/com/umc/networkingService/domain/album/dto/response/AlbumPageResponse.java
  src/main/java/com/umc/networkingService/domain/album/dto/response/AlbumPagingResponse.java
  src/main/java/com/umc/networkingService/domain/album/entity/Album.java
  src/main/java/com/umc/networkingService/domain/album/entity/AlbumComment.java
  src/main/java/com/umc/networkingService/domain/album/entity/AlbumHeart.java
  src/main/java/com/umc/networkingService/domain/album/entity/AlbumImage.java
  src/main/java/com/umc/networkingService/domain/album/mapper/AlbumCommentMapper.java
  src/main/java/com/umc/networkingService/domain/album/mapper/AlbumHeartMapper.java
  src/main/java/com/umc/networkingService/domain/album/mapper/AlbumImageMapper.java
  src/main/java/com/umc/networkingService/domain/album/mapper/AlbumMapper.java
  src/main/java/com/umc/networkingService/domain/album/repository/AlbumCommentRepository.java
  src/main/java/com/umc/networkingService/domain/album/repository/AlbumHeartRepository.java
  src/main/java/com/umc/networkingService/domain/album/repository/AlbumImageRepository.java
  src/main/java/com/umc/networkingService/domain/album/repository/AlbumRepository.java
  src/main/java/com/umc/networkingService/domain/album/repository/AlbumRepositoryCustom.java
  src/main/java/com/umc/networkingService/domain/album/repository/AlbumRepositoryCustomImpl.java
  src/main/java/com/umc/networkingService/domain/album/service/AlbumCommentService.java
  src/main/java/com/umc/networkingService/domain/album/service/AlbumCommentServiceImpl.java
  src/main/java/com/umc/networkingService/domain/album/service/AlbumImageService.java
  src/main/java/com/umc/networkingService/domain/album/service/AlbumImageServiceImpl.java
  src/main/java/com/umc/networkingService/domain/album/service/AlbumService.java
  src/main/java/com/umc/networkingService/domain/album/service/AlbumServiceImpl.java
  src/main/java/com/umc/networkingService/global/common/exception/code/AlbumCommentErrorCode.java
  src/main/java/com/umc/networkingService/global/common/exception/code/AlbumErrorCode.java
Labels: ✨ feature

#73 [FEAT] board Dummy Data 생성
  src/main/java/com/umc/networkingService/domain/board/controller/BoardController.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/BoardCommentResponse.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/BoardResponse.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/MyBoardResponse.java
  src/main/java/com/umc/networkingService/domain/board/service/BoardFileService.java
  src/main/java/com/umc/networkingService/domain/board/service/BoardFileServiceImpl.java
  src/main/java/com/umc/networkingService/domain/board/service/BoardService.java
  src/main/java/com/umc/networkingService/domain/board/service/BoardServiceImpl.java
  src/main/java/com/umc/networkingService/domain/branch/service/BranchUniversityService.java
  src/main/java/com/umc/networkingService/domain/branch/service/BranchUniversityServiceImpl.java
  src/main/java/com/umc/networkingService/domain/member/service/AuthService.java
  src/main/java/com/umc/networkingService/domain/member/service/AuthServiceImpl.java
  src/main/java/com/umc/networkingService/domain/test/controller/TestController.java
  src/main/java/com/umc/networkingService/domain/test/service/MemberDummyInfo.java
  src/main/java/com/umc/networkingService/domain/test/service/TestService.java
  src/main/java/com/umc/networkingService/domain/university/service/UniversityService.java
  src/main/java/com/umc/networkingService/domain/university/service/UniversityServiceImpl.java
Labels: ✨ feature

#81 [FEAT] 프로젝트 좋아요 API 추가
  src/main/java/com/umc/networkingService/domain/project/controller/ProjectController.java
  src/main/java/com/umc/networkingService/domain/project/dto/response/ProjectAllResponse.java
  src/main/java/com/umc/networkingService/domain/project/dto/response/ProjectDetailResponse.java
  src/main/java/com/umc/networkingService/domain/project/dto/response/ProjectLikeResponse.java
  src/main/java/com/umc/networkingService/domain/project/entity/Project.java
  src/main/java/com/umc/networkingService/domain/project/entity/ProjectHeart.java
  src/main/java/com/umc/networkingService/domain/project/mapper/ProjectMapper.java
  src/main/java/com/umc/networkingService/domain/project/repository/ProjectHeartRepository.java
  src/main/java/com/umc/networkingService/domain/project/service/ProjectService.java
  src/main/java/com/umc/networkingService/domain/project/service/ProjectServiceImpl.java
Labels: ✨ feature

#87 [FEAT] 스케줄 더미 데이터 및 스케줄 조회 API 수정
  src/main/java/com/umc/networkingService/domain/schedule/controller/ScheduleController.java
  src/main/java/com/umc/networkingService/domain/schedule/controller/StaffScheduleController.java
  src/main/java/com/umc/networkingService/domain/schedule/service/ScheduleService.java
  src/main/java/com/umc/networkingService/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/com/umc/networkingService/domain/test/controller/TestController.java
  src/main/java/com/umc/networkingService/domain/test/service/TestService.java
Labels: ✨ feature, 🐛 bug

#89 [FEAT] web용 ìTIL 일별 조회 API 구현
  src/main/java/com/umc/networkingService/domain/todayILearned/controller/TodayILearnedController.java
  src/main/java/com/umc/networkingService/domain/todayILearned/dto/response/TodayILearnedResponse.java
  src/main/java/com/umc/networkingService/domain/todayILearned/mapper/TodayILearnedMapper.java
  src/main/java/com/umc/networkingService/domain/todayILearned/service/TodayILearnedService.java
  src/main/java/com/umc/networkingService/domain/todayILearned/service/TodayILearnedServiceImpl.java
  src/main/resources/application-local.yml
Labels: ✨ feature

#91 [FEAT] 홈화면 핀고정된 공지 조회 api
  src/main/java/com/umc/networkingService/domain/board/controller/BoardController.java
  src/main/java/com/umc/networkingService/domain/board/dto/response/BoardResponse.java
  src/main/java/com/umc/networkingService/domain/board/mapper/BoardMapper.java
  src/main/java/com/umc/networkingService/domain/board/repository/BoardRepositoryCustom.java
  src/main/java/com/umc/networkingService/domain/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/umc/networkingService/domain/board/service/BoardService.java
  src/main/java/com/umc/networkingService/domain/board/service/BoardServiceImpl.java
Labels: ✨ feature, 🐛 bug
